### ISSUE TITLE
add cache busting url to css images

### ISSUE THREAD

**Issue by zebapy** [middlebury/frontend#172]
need to add `?fv=<build time>` or similar to css image paths 

related to https://github.com/middlebury/drupal8/issues/642

**Comment by zebapy** [comment]
@adamfranco would you say JS `Date.now()` would suffice? 

I know it's not perfect because it's not a content hash

```css

.site-header__logo {
  display: block;
  background-image: url("/images/miis-logo.svg?fv=1556738150311");
  background-repeat: no-repeat;
  width: 213px;
  height: 40px;
  text-indent: -9999px; }
  @media (min-width: 960px) {
    .site-header__logo {
      background-image: url("/images/miis-shield.svg?fv=1556738150312");
      width: 52px;
      height: 58px; }
      .home .site-header__logo,
      .site-header.is-toggled .site-header__logo {
        background-image: url("/images/miis-logo.svg?fv=1556738150312");
        width: 305px;
        height: 58px; } }
```
